export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const ADD_BASKET = 'ADD_BASKET'
export const REMOVE_BASKET = 'REMOVE_BASKET'
export const RESET_BASKET = 'RESET_BASKET'
